config/routes.rb
Rails.application.routes.draw do
  
  resources :questions
  # get 'question/new'

  # get 'question/create'

  # get 'question/update'

  # get 'question/edit'

  # get 'question/destroy'

  # get 'question/index'

  # get 'question/show'

  devise_for :users
  
  resources :advertisements
  # get 'advertisements/index'

  # get 'advertisement/show'

  # get 'posts/index'

  # get 'posts/show'

  # get 'posts/new'

  # get 'posts/edit'

  # get 'welcome/index'
  resources :posts
  # resources :posts, except: [:show]
  # get 'welcome/about'
  get 'about' => 'welcome#about'
  
  # get 'welcome/contact'
  get 'contact' => 'welcome#contact'

  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments
    
    # def title
    #     raise
    # end
end

app/models/question.rb
 class Question < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  def index
    @advertisements = Advertisement.all
  end

  def show
    @advertisement = Advertisement.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end
  
  def create
     @post = Post.new(params.require(:post).permit(:title, :body))
     if @post.save
       flash[:notice] = "Post was saved."
       redirect_to @post
     else
       flash[:error] = "There was an error saving the post. Please try again."
       render :new
     end
   end

  
  def edit
     @post = Post.find(params[:id])
  end

   def update
     @post = Post.find(params[:id])
     if @post.update_attributes(params.require(:post).permit(:title, :body))
       flash[:notice] = "Post was updated."
       redirect_to @post
     else
       flash[:error] = "There was an error saving the post. Please try again."
       render :edit
     end
   end
   
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
     @questions = Question.all
  end
  
  def show
    @question = Question.find(params[:id])
  end
  
  def new
    @question = Question.new
  end

  def create
     @question = Question.new(params.require(:question).permit(:title, :body, :resolved))
     if @question.save
       flash[:notice] = "Question was saved."
       redirect_to @question
     else
       flash[:error] = "There was an error saving the question. Please try again."
       render :new
     end
  end

  def update
    @question = Question.find(params[:id])
     if @question.update_attributes(params.require(:question).permit(:title, :body, :resolved))
       flash[:notice] = "Question was updated."
       redirect_to @question
     else
       flash[:error] = "There was an error saving the question. Please try again."
       render :edit
     end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def destroy
    @question = Question.destroy(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
  
  def contact
  end
  
end

app/helpers/advertisement_helper.rb
module AdvertisementHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def my_name
        "Dan Williams"
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/advertisements/index.html.erb
<!--<h1>Advertisement#index</h1>-->
<!--<p>Find me in app/views/advertisement/index.html.erb</p>-->
<h1>All Advertisements</h1>
<% @advertisements.each do |advertisement| %>
    <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
          <%= link_to advertisement.title, advertisement %>
       </h4>
     </div>
   </div>
<% end %>

app/views/advertisements/show.html.erb
<!--<h1>Advertisement#show</h1>-->
<!--<p>Find me in app/views/advertisement/show.html.erb</p>-->
<h1><%= @advertisement.title %></h1>
<p><%= @advertisement.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewOptions</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  
    <div class="container">
      <ul>
        <ul class="nav nav-tabs">
          <li><%= link_to "Bloccit", root_path %></li>
          <li><%= link_to "About", about_path %></li>
      </ul>
      
      <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

    <%= yield %>
    </div>

  </body>
</html>

app/views/posts/edit.html.erb
<!--<h1>Posts#edit</h1>-->
<!--<p>Find me in app/views/posts/edit.html.erb</p>-->

<h1>Edit Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure the it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @post do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/posts/index.html.erb
<!--<h1>Posts#index</h1>-->
<!--<p>Find me in app/views/posts/index.html.erb</p>-->
<h1>All Posts</h1>
<% @posts.each do |post| %>
    <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to post.title, post %>
       </h4>
     </div>
   </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @post do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/posts/show.html.erb
<!--<h1>Posts#show</h1>-->
<!--<p>Find me in app/views/posts/show.html.erb</p>-->
<h1><%= @post.title %></h1>
 
 <%= link_to "Edit", edit_post_path(@post), class: 'btn btn-success' %>
 
<p><%= @post.body %></p>

app/views/questions/create.html.erb
<h1>Question#create</h1>
<p>Find me in app/views/question/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Question#destroy</h1>
<p>Find me in app/views/question/destroy.html.erb</p>

app/views/questions/edit.html.erb
<h1>Edit Questions</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for Questions</p>
     <ul>
       <li>Make sure the its a good question.</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @question do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter question title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
       </div>
       <div>
        <div class="form-group">
         <%= f.label :resolved %>
         <%= f.check_box :resolved %>
        </div>
        
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/questions/index.html.erb
<!--<h1>Question#index</h1>-->
<!--<p>Find me in app/views/question/index.html.erb</p>-->
<h1>All Questions</h1>
<% @questions.each do |question| %>
    <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to question.title, question %>
       </h4>
     </div>
   </div>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for Questions</p>
     <ul>
       <li>Questions should relate to the post.</li>
       <li>No profanity please or personal remarks.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @question do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter Question title" %>
       </div>

       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question body" %>
       </div>

       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/questions/show.html.erb
<!--<h1>Question#show</h1>-->
<!--<p>Find me in app/views/question/show.html.erb</p>-->

<h1><%= @question.title %></h1>
<p><%= @question.resolved %></p>

 <%= link_to "Edit", edit_question_path(@question), class: 'btn btn-success' %>

<p><%= @question.body %></p>

app/views/questions/update.html.erb
<h1>Question#update</h1>
<p>Find me in app/views/question/update.html.erb</p>

app/views/welcome/about.html.erb
<h1>About Bloccit</h1>
<!--<p>Created by: Dan Williams</p>-->
<p>Created by: <%= my_name %></p>

<%= link_to "Follow me", "http://www.facebook.com/trybloc", class: "social-btn" %>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to Bloccit</h1>
<p>This is the home page for Bloccit</p>
<!--<p id="index-title">This is the home page for Bloccit</p>-->

<!--  <div class="posts">Post 1 goes here.</div>-->
<!--  <div class="posts">Post 2 goes here.</div>-->
  
<!--    <section>I am the content in a section element.</section>-->
    